# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '比价' do

pod 'AFNetworking'
pod 'BlocksKit'
pod 'CocoaLumberjack'
pod 'Masonry'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'Shimmer'
pod 'RESideMenu'
pod 'WMPageController'

end

